apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: liormilliger@gmail.com 
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - http01:
        ingress:
          class: alb
          podTemplate:
            metadata:
              annotations:
                alb.ingress.kubernetes.io/group.name: "cloudride-app-group"
                alb.ingress.kubernetes.io/scheme: "internet-facing"
