apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.14.0
    helm:
      values: |
        clusterName: liorm-cloudride-test
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::753392824297:role/liorm-cloudride-test-alb-controller-role
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true