apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      # IMPORTANT: Use your correct AWS region
      region: us-west-2
      auth:
        # This tells ESO to use the attached service account
        jwt:
          serviceAccountRef:
            name: external-secrets 
            namespace: external-secrets