apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: git@github.com:liormilliger/cloudride-k8s.git
    targetRevision: main
    path: my-app-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

