apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-credentials
  # IMPORTANT: Change this to the namespace where your website-app is deployed
  namespace: default
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore # We are referencing the resource created above
  target:
    name: rds-credentials-k8s # This is the NAME of the K8s Secret that will be created
    creationPolicy: Owner
    # Optional: Set secret type if needed, e.g., kubernetes.io/basic-auth
    # template: 
    #   type: Opaque
  data:
  - secretKey: db_username # The key in the K8s Secret
    remoteRef:
      key: ${var.RDS_SECRET_NAME} # The name of the secret in AWS Secrets Manager (assuming it is the same as the TF variable)
      property: username # The key within the JSON secret stored in AWS
  - secretKey: db_password # The key in the K8s Secret
    remoteRef:
      key: ${var.RDS_SECRET_NAME}
      property: password