apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-credentials
  namespace: default
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: rds-credentials-k8s
    creationPolicy: Owner
  data:
  - secretKey: db_username
    remoteRef:
      key: rds!db-ef76ec0b-780c-4e4b-a8d6-45d22333ed19
      property: username
  - secretKey: db_password
    remoteRef:
      key: rds!db-ef76ec0b-780c-4e4b-a8d6-45d22333ed19
      property: password